dataset:
  load_metric: Daily_TSS
  performance_metric: Garmin VO2
  filter_sport: ['Bike']

train:
  initial_guess: [0.5, 0.5, 55, 45, 7]
  bounds: [(.1,1.90), (.1,2.90), (30,70), (30,50), (5,14)]


