dataset:
  load_metric: Daily_TSS
  performance_metric: Garmin VO2
  filter_sport: ['Bike']

train:
  initial_guess: [0.5, 0.5, 58, 45, 7]
  bounds: [[0.10,1.90], [0.10,2.90], [50,70], [30,50], [5,14]]
  output_plot: True


